version: "3.8"

services:
  ngnix:
    build: ./requirements/ngnix
    ports:
      - "443:443"
    restart : on-failure
    volumes : 
      - wp:/var/www/html/
    depends_on:
      - mariadb
    networks:
      - inc-network
  mariadb:
    build : ./requirements/mariadb
    ports:
      - "3306:3306"
    env_file:
      ./.env
    restart : on-failure
    volumes :
      - db:/var/lib/mysql
    networks:
      - inc-network
  wordpress :
    build : ./requirements/wordpress
    restart : on-failure
    volumes : 
      - wp:/var/www/html/
    depends_on:
      - mariadb
      - ngnix
    networks:
      - inc-network

volumes :
  db :
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/db
  wp :
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/wp

networks:
    inc-network:
        driver: bridge
