version: "3.8"

services:
  mariadb:
    build : ./requirements/mariadb
    # ports:
    #   - "3306:3306"
    restart : always
    networks:
      - inc-network
    volumes :
      - db:/var/lib/mysql
    env_file:
      ./.env
  wordpress :
    build : ./requirements/wordpress
    restart : always
    volumes : 
      - wp:/var/www/html/
    networks:
      - inc-network
    depends_on:
      - mariadb
    # ports:
    #   - "9000:9000"
    env_file:
      ./.env
  nginx:
    build: ./requirements/ngnix
    ports:
      - "443:443"
    restart : always
    volumes : 
      - wp:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inc-network
  redis :
    build : ./requirements/bonus/redis/
    restart : always
    # ports :
    #   - "6379:6379"
    depends_on:
      - wordpress
    networks:
      - inc-network
  adminer :
    build : ./requirements/bonus/adminer
    restart : always
    volumes : 
      - wp:/var/www/html/
    networks:
      - inc-network
    depends_on:
      - wordpress
  ctfchallenge:
    build: ./requirements/bonus/ctfchallenge/
    ports:
      - "1337:1337"
    restart : always
  portfolio:
    build: ./requirements/bonus/portfolio/
    ports:
      - "6969:6969"
    restart : always
  ftp:
    build: ./requirements/bonus/ftp/
    ports:
      - "20:20"
      - "21:21"
      - "40000-40100:40000-40100"
    restart : always
    volumes : 
      - wp:/var/www/html/
    networks:
      - inc-network
    depends_on:
      - wordpress
    env_file:
      ./.env

volumes :
  db :
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/db
  wp :
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/wp

networks:
    inc-network:
        driver: bridge
