version: "3.8"

services:
  mariadb:
    build : ./requirements/mariadb
    ports:
      - "3306:3306"
    restart : always
    networks:
      - inc-network
    volumes :
      - db:/var/lib/mysql
    env_file:
      ./.env
  wordpress :
    build : ./requirements/wordpress
    restart : always
    volumes : 
      - wp:/var/www/html/
    networks:
      - inc-network
    depends_on:
      - mariadb
    env_file:
      ./.env
    ports:
      - "9000:9000"
  ngnix:
    build: ./requirements/ngnix
    ports:
      - "443:443"
    restart : always
    volumes : 
      - wp:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inc-network
  ctfchallenge:
    build: ./requirements/bonus/ctfchallenge/
    ports:
      - "1337:1337"
    restart : always
  portfolio:
    build: ./requirements/bonus/portfolio/
    ports:
      - "6969:6969"
    restart : always
  ftp:
    build: ./requirements/bonus/ftp/
    ports:
      - "20:20"
      - "21:21"
    restart : always

volumes :
  db :
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/db
  wp :
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/wp

networks:
    inc-network:
        driver: bridge
