FROM debian
## TODO : check wp-cli

VOLUME /var/www/html

RUN apt update

# installing wordpress dependencies
RUN apt install php php-curl php-fpm php-bcmath php-gd php-soap php-zip php-curl php-mbstring php-mysqlnd php-gd php-xml php-intl php-zip curl -y
#
# # downloading wordpress files
WORKDIR /var/www/html/

RUN curl https://wordpress.org/latest.tar.gz -O
RUN tar -zxvf latest.tar.gz
RUN mv wordpress/* .
RUN rm -rf wordpress lastest.tar.gz

COPY tools/* .

RUN curl -s https://api.wordpress.org/secret-key/1.1/salt/ >> wp-config.php

# # chaning premissions
RUN chown -R www-data:www-data /var/www/html
RUN chmod -R 777 wp-config.php

RUN chmod +x setup.sh
USER www-data

CMD ["./setup.sh"]
